apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::162563910550:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZCCJ8BP70QDO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::162563910550:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-24T21:24:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1582"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a641d75c-a178-4e4d-a096-65c25d008755
